sonar.projectKey=Davincci2713_FRONTEND_PROYECTO_WCH
sonar.organization=davincci2713

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=FRONTEND_PROYECTO_WCH
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*Test.dart
# sonar.coverageReportPaths=coverage/lcov.info
sonar.dart.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**/*.dart

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.language=dart
