// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalooS6BePPtPGHXhP8o6S00pahGzBWAE',
    appId: '1:810022980430:web:9ecd5344ad5ac10adbac1f',
    messagingSenderId: '810022980430',
    projectId: 'world-cup-hub-b92b8',
    authDomain: 'world-cup-hub-b92b8.firebaseapp.com',
    storageBucket: 'world-cup-hub-b92b8.firebasestorage.app',
    measurementId: 'G-D8845GPVEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-u66hbMopveZu7Jy3IS8Q33gTepzbf5U',
    appId: '1:810022980430:android:9c1570d5e1def9d3dbac1f',
    messagingSenderId: '810022980430',
    projectId: 'world-cup-hub-b92b8',
    storageBucket: 'world-cup-hub-b92b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbEcm9zt0F4LLGxrq8RwswEkqMbrwgng',
    appId: '1:810022980430:ios:9fc9e0540405b680dbac1f',
    messagingSenderId: '810022980430',
    projectId: 'world-cup-hub-b92b8',
    storageBucket: 'world-cup-hub-b92b8.firebasestorage.app',
    iosBundleId: 'com.example.frontendProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbEcm9zt0F4LLGxrq8RwswEkqMbrwgng',
    appId: '1:810022980430:ios:9fc9e0540405b680dbac1f',
    messagingSenderId: '810022980430',
    projectId: 'world-cup-hub-b92b8',
    storageBucket: 'world-cup-hub-b92b8.firebasestorage.app',
    iosBundleId: 'com.example.frontendProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalooS6BePPtPGHXhP8o6S00pahGzBWAE',
    appId: '1:810022980430:web:d25ff24e2a89039edbac1f',
    messagingSenderId: '810022980430',
    projectId: 'world-cup-hub-b92b8',
    authDomain: 'world-cup-hub-b92b8.firebaseapp.com',
    storageBucket: 'world-cup-hub-b92b8.firebasestorage.app',
    measurementId: 'G-39S1RX7T84',
  );
}
